development: &development
  host: localhost
  adapter: postgresql
  database: mymarketprices_dev
  username: robocast
  password: robocast

qa:
  <<: *development

production:
  host: dbprices.ru
  adapter: postgresql
  database: mymarketprices
  username: deployer
  password: deployerDBpass

test:
  <<: *development
  database: mymarketprices_test
