development: &development
  host: localhost
  adapter: postgresql
  database: mymarketprices_dev
  username: robocast
  password: robocast

qa:
  <<: *development

production:
  <<: *development

test:
  <<: *development
  database: mymarketprices_test
